# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package definition files
COPY package.json package-lock.json tsconfig.json ./

# Copy source
COPY src ./src

# Install dependencies and build
RUN npm ci --ignore-scripts && npm run build

# Expose stdio, no ports
CMD ["node", "build/index.js"]
