# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js LTS on Alpine for small footprint
FROM node:lts-alpine AS builder

# Install build dependencies
RUN apk add --no-cache git python3 make g++

# Create app directory
WORKDIR /usr/src/app

# Copy package files
COPY package.json package-lock.json tsconfig.json ./
# Copy source
COPY src ./src

# Install dependencies and build
RUN npm install && npm run build

# Production image
FROM node:lts-alpine

WORKDIR /usr/src/app

# Copy built files and production dependencies
COPY package.json package-lock.json ./
RUN npm install --production
COPY --from=builder /usr/src/app/build ./build

# Default command will be provided by MCP start command
CMD ["node", "build/index.js"]
