# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package*.json tsconfig.json .
RUN npm ci --ignore-scripts

# Copy source
COPY . .

# Build TypeScript
RUN npm run build

# Expose no ports (stdio)
# Run the MCP server
CMD ["node", "build/index.js"]
